// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA43lD3OcKYbYLAQqloEmKN5T8N9Gcw5kk',
    appId: '1:499367403075:web:92b2685a7a0b50acdb7ef6',
    messagingSenderId: '499367403075',
    projectId: 'beauty-scanner-7e323',
    authDomain: 'beauty-scanner-7e323.firebaseapp.com',
    databaseURL: 'https://beauty-scanner-7e323-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-scanner-7e323.appspot.com',
    measurementId: 'G-4DEC9MRSS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6iB0cgKYa4vWbjT1C3UOPbbtQ4eIAyX4',
    appId: '1:499367403075:android:5de867dfb2bb715cdb7ef6',
    messagingSenderId: '499367403075',
    projectId: 'beauty-scanner-7e323',
    databaseURL: 'https://beauty-scanner-7e323-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-scanner-7e323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKjAWlzr9bE4QbjK2qajfvEDhCdF1ALwQ',
    appId: '1:499367403075:ios:08379cabca0f11ffdb7ef6',
    messagingSenderId: '499367403075',
    projectId: 'beauty-scanner-7e323',
    databaseURL: 'https://beauty-scanner-7e323-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-scanner-7e323.appspot.com',
    iosBundleId: 'com.example.tccFlutter7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKjAWlzr9bE4QbjK2qajfvEDhCdF1ALwQ',
    appId: '1:499367403075:ios:b3d54df256e9c8bcdb7ef6',
    messagingSenderId: '499367403075',
    projectId: 'beauty-scanner-7e323',
    databaseURL: 'https://beauty-scanner-7e323-default-rtdb.firebaseio.com',
    storageBucket: 'beauty-scanner-7e323.appspot.com',
    iosBundleId: 'com.example.tccFlutter7.RunnerTests',
  );
}
